[package]
name = "telegram-chatgpt-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openai_chatgpt_api = "0.1.2"
teloxide = "0.12.2"
